services:
  - type: web
    name: zentra-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: SMTP_FROM
        value: Zentra <onboarding@resend.dev>
      - key: NODE_ENV
        value: production