services:
  - type: web
    name: zentra-api
    runtime: node
    plan: free
    buildCommand: npm ci && npx prisma generate --schema=apps/api/prisma/schema.prisma && cd apps/api && npx nest build
    startCommand: cd apps/api && npx prisma db push --skip-generate && node dist/main
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: RESEND_API_KEY
        sync: false
      - key: SMTP_FROM
        value: Zentra <onboarding@resend.dev>
      - key: NODE_ENV
        value: production